FROM node:14
WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn
RUN yarn global add nodemon

COPY ./src/ ./src/
COPY ./build/ ./build/
COPY .env index.js webpack.config.js blagues.json ./

EXPOSE 3001

CMD nodemon index.js
