FROM node:17.2.0
WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3000
EXPOSE 4000

CMD npx nodemon --watch '**/*' --ext 'ts,js' --ignore 'sw.js' --exec 'npx ts-node src/index.ts'
