FROM node:17.2
WORKDIR /app

COPY --chown=node:node package*.json ./
COPY --chown=node:node tsconfig.json ./

RUN npm install

COPY --chown=node:node ./src ./src
COPY --chown=node:node ./prisma ./prisma
COPY --chown=node:node .env .

RUN npx prisma generate

EXPOSE 4000

USER node

CMD npx nodemon --watch '**/*' --ext 'ts,js' --ignore 'sw.js' --exec 'npx ts-node src/index.ts'
