FROM node:20.18.0
WORKDIR /app

COPY --chown=node:node package.json yarn.lock ./
COPY --chown=node:node tsconfig.json ./

RUN yarn install

COPY --chown=node:node ./src ./src
COPY --chown=node:node ./prisma ./prisma
COPY --chown=node:node .env .

RUN npx prisma generate

ENV NODE_ENV=developement

ENV NODE_OPTIONS="--enable-source-maps"

EXPOSE 4000

CMD npx tsc-watch --onSuccess "node dist/index.js"
