FROM node:18.4
WORKDIR /app

COPY --chown=node:node package.json yarn.lock ./
COPY --chown=node:node tsconfig.json ./

RUN yarn install

COPY --chown=node:node ./src ./src
COPY --chown=node:node ./prisma ./prisma
COPY --chown=node:node .env .

RUN npx prisma generate

EXPOSE 4000

CMD npx tsc-watch --onSuccess "node dist/index.js"
